# Generated by Django 3.1.5 on 2021-01-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210115_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='author',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='name',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
    ]
