# Generated by Django 3.1.5 on 2021-01-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_blog_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255),
        ),
    ]
