# Generated by Django 3.1.5 on 2021-01-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210129_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
