# Generated by Django 3.1.5 on 2021-01-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210129_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_cover',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
